package API;

public class Actions {
    /**
     acceptEnterpriseJoinRequest
     addAdminToBoard
     addAdminToOrganization
     addAttachmentToCard
     addBoardsPinnedToMember
     addChecklistToCard
     addLabelToCard
     addMemberToBoard
     addMemberToCard
     addMemberToOrganization
     addOrganizationToEnterprise
     addToEnterprisePluginWhitelist
     addToOrganizationBoard
     commentCard
     convertToCardFromCheckItem
     copyBoard
     copyCard
     copyChecklist
     createLabel
     copyCommentCard
     createBoard
     createBoardInvitation
     createBoardPreference
     createCard
     createChecklist
     createList
     createOrganization
     createOrganizationInvitation
     deleteAttachmentFromCard
     deleteBoardInvitation
     deleteCard
     deleteCheckItem
     deleteLabel
     deleteOrganizationInvitation
     disableEnterprisePluginWhitelist
     disablePlugin
     disablePowerUp
     emailCard
     enableEnterprisePluginWhitelist
     enablePlugin
     enablePowerUp
     makeAdminOfBoard
     makeAdminOfOrganization
     makeNormalMemberOfBoard
     makeNormalMemberOfOrganization
     makeObserverOfBoard
     memberJoinedTrello
     moveCardFromBoard
     moveCardToBoard
     moveListFromBoard
     moveListToBoard
     removeAdminFromBoard
     removeAdminFromOrganization
     removeBoardsPinnedFromMember
     removeChecklistFromCard
     removeFromEnterprisePluginWhitelist
     removeFromOrganizationBoard
     removeLabelFromCard
     removeMemberFromBoard
     removeMemberFromCard
     removeMemberFromOrganization
     removeOrganizationFromEnterprise
     unconfirmedBoardInvitation
     unconfirmedOrganizationInvitation
     updateBoard
     updateCard
     updateCheckItem
     updateCheckItemStateOnCard
     updateChecklist
     updateLabel
     updateList
     updateMember
     updateOrganization
     voteOnCard
     **/
}
